### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by gamemodeop** [MattyIce/postpromoter#76]
Hello,
If I try to start the bot there is this Error message:
Error: Cannot find module 'steem'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/postpromoter/postpromoter.js:2:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I hope someone can help me
Eith best regards
Florian

**Comment by MattyIce** [comment]
Run ```$ npm install``` first to install the required packages.
