### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by Vegito03** [MattyIce/postpromoter#97]
Hey there I am facing this issue can anyone has solution of it. I just changed my bot owner name , account name and the private keys in postpromoter.js file but getting this error here's the error down below

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/postpromoter/postpromoter.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by SuggeElson** [comment]
npm install request -g

**Comment by Vegito03** [comment]
I also tried this but not working
I execute the file by "node postpromoter.js"
As nodejs isn't working
